---
###Configure Password Auth

- name: Double Check
  debug:
    msg:
      - "student_name: {{ student_name }}"
      - "password {{ admin_password }}"

- name: Create User Group
  group:
    name: "{{ student_name }}"
    state: present

- name: Create User Account
  user:
    createhome: yes
    group: "{{ student_name }}"
    name: "{{ student_name }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"

- name: Include Red Hat tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

- name: Configure sshd and sudoers
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
    validate: "{{ item.validate | default(omit) }}"
    backup: no
  with_items: "{{ common_node_config_options }}"
  notify: restart ssh
  tags:
    - ssh
    - sudo
    - common

- meta: flush_handlers
  tags:
    - common

#tasks file for cloud-student
- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags:
    - control

- name: Install base packages
  yum:
    name:
      - vim
      - git
    state: latest
    enablerepo: epel-testing
  tags:
    - control

- name: Install Ansible
  yum:
    name:
      - sshpass
      - ansible
    state: latest
    enablerepo: rhui-REGION-rhel-server-extras
  tags:
    - control

- name: Clone lightbulb repo
  git:
    accept_hostkey: yes
    clone: yes
    dest: ~{{ username }}/lightbulb
    repo: https://github.com/network-automation/lightbulb.git
    force: yes
  tags:
    - lightbulb

- name: Move networking workshop folder to correct location
  command: cp -r /tmp/lightbulb/workshops/networking/ /home/{{student_name}}/networking-workshop
  tags:
    - lightbulb

- name: fix permissions of networking-workshop
  file:
    path: /home/{{ student_name }}/networking-workshop
    owner: "{{ student_name }}"
    group: "{{ student_name }}"
    recurse: yes
#- name: Clone networking repo
#  local_action:
#    module:  git
#    accept_hostkey: yes
#    clone: yes
#    dest: /tmp/lightbulb
#    repo: https://github.com/network-automation/lightbulb.git
#    force: yes
#  ignore_errors: yes
#  become: no
#  run_once: True
#  tags:
#    - control
#    - lightbulb

# not fast b/c of https://github.com/ansible/ansible/issues/21513
#- name: Grab Networking Workshop (directory) from Git repo
#  copy:
#    src: /tmp/lightbulb/workshops/networking/
#    dest: /home/{{student_name}}/networking-workshop
#    force: yes
#  become_user: "{{student_name}}"
#  ignore_errors: yes
#  tags:
#    - control
#    - lightbulb

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ student_name }}/networking-workshop/lab_inventory
    owner: "{{ student_name }}"
    group: "{{ student_name }}"
  tags:
    - control

- name: Override /etc/ansible/hosts
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    owner: "{{ student_name }}"
    group: "{{ student_name }}"

- name: Install ansible.cfg and vimrc in home directory
  template:
    src: vimrc.j2
    dest: ~{{ student_name }}/.vimrc
    owner: "{{ student_name }}"
    group: "{{ student_name }}"

- name: Put student inventory in proper spot
  copy:
    src: ./{{ student_name }}.{{workshop_name}}.hosts
    dest: "{{ control_node_inventory_path }}"
    owner: "{{ student_name }}"
    group: "{{ student_name }}"

- name: setup /etc/hosts file per student
  copy:
    src: ./{{ student_name }}.{{workshop_name}}.etchosts
    dest: "/etc/hosts"
    owner: "{{ student_name }}"
    group: "{{ student_name }}"
  tags:
    - etchosts

- name: Put ssh-key in proper spot
  copy:
    src: ./{{workshop_name}}_key
    dest: "/home/{{student_name}}/.ssh/"
    owner: "{{ student_name }}"
    group: "{{ student_name }}"
  tags:
    - testing

- name: change permissions on ssh-key file
  file:
    path: "/home/{{student_name}}/.ssh/{{workshop_name}}_key"
    mode: 0400
  tags:
    - testing

- name: copy over ssh config file
  template:
    src: sshconfig.j2
    dest: /home/{{student_name}}/.ssh/config
    owner: "{{student_name}}"
    group: "{{student_name}}"
  tags:
    - testing

- name: change permissions on ssh config file
  file:
    path: "/home/{{student_name}}/.ssh/config"
    mode: 0700
  tags:
    - testing
